{% set name = "latex-decode" %}
{% set version = "0.4.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: e2606bd0584fc5393f2a4b9ef907ff48573b8bad4013bda9c9f8c2c7ffb0bdf8

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name|replace('-','/') }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: GPL-3.0
  license_family: GPL
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: Decodes strings formatted in LaTeX to equivalent Unicode strings.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/inukshuk/{{ name }}

extra:
  recipe-maintainers:
    - sodre
