travis:
  secure:
    BINSTAR_TOKEN: GFuleGiPwnq3a3e+0LOG979RAano+0YKEXgMrLaP6PelVRIrofgNpN6hMW1kGxsrwtFDv5FObjY0eDQJ5fFDI1RKrDEY33l9m4uuICXtCXqr5P31aERcT4fd/YeevW5I1UM0wIxFVx0C56jtG3Mwwne1l7q3IDa6h7wDUDiun9Ce/SP5oqbMC1VR/7vFal1ya2Mov3vncrqaOhewiKKD//OEpa4SN4ydR8pNpymNmANAp4V3vwSzfymqcaZ+J1FivWsUW0vQGEpV/2shiE7uRgLz5qXvV+9ZFS3GN6IRdgO+lkAX2GaVgwkOpFRPdXhhrsj87Xr4LeNkPbFX3JIJFog8V/hTXWQdBAlKjpatF59hL8VSIrALngZkGUt1YM9KSHUQgfxUy6SSpESHaAZrx23yZRMkog2F0Gf+d+IQll9yEAqNmykx7c+IWAyTFUTw7294MKRNcUg5KehdkV/BmWZlrGhioFIBddB79zTvzYeEAAgOkUzn85euXQIUPtuhuZ3bs2kUu1A4TqIS+eA0y3Nir0GAla8RKsooH5opYUjOWyqF1y+A47Xdn58JRXOH41SAlhK1upYhkFHWLxjHMgOlOy9r1Sr/TN7OZnaRKgeYX7nYJHAS820s/dvf+mbuXn+k1336eQK3RpvZBCI7UQIySVimmVJPv0KwVL+XtMU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
