travis:
  secure:
    BINSTAR_TOKEN: jI1WQGxK70snuw62v43zXtrg35qmiErbpDRXC+HEzViYZ/YXT1wEijp0/HElMyO0b7SmXesuefv1tx50Vt8seNIZjF0Szt9siZiTgjdM9TK18+H78SOPYlRi17BZYdtFwxgNMVjbFJVx/gVIEHpxKHU4KbvCGfafNDqABvHg8AZmQYslBWQTJLAfblff9U7wXlCOUTq94CXtk1GXdWCJ1gZNO6XRx/i/HlxMQBcn7lW3WykrqKFQAVOj6SxUIPQCV82r9GNb6qexuGVf7VKhUVnDuQLi9nx3lpC1fYjcivWPjUtN14qzlHFp3YTHQV1h1dAa9jeACZh/wsX8QGztokC2yrc3v9cS6Gh2uPDr9Tr3LnNTuVCJdJMUR1CCRIcT1hXLAty9yAMYmqCcTF0GY3bSKhXQZKMimUBDn/NibwmNUlMG/lIuUXbBYuxoiXrJgKYsvDn6i4krAA0hg48O09dj8nksU+6y7Kf0OOz8sse8TYSHkdgPFyGlLrHfXKPh9TL/8wL3RO8xvmLkfURGbmi5rUeOiZ3ssH0uvlM2SpESWWGES5XuLRY0JRDCGKQY0942CCZ/I1LCBNc//TTVldq+vsQGpB8sKk49cnIkonLeBcIeggn9+VRkgzM12VNpdK3fxCX5q+d/cRjPvlLUq3ja+Zn7cO2Ziii+SHGBJc8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
